spring :
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://211.222.25.101:5432/ATproject7
    username: ATproject7
    password: at1234
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
mybatis:
  mapper-locations: classpath:mappers/*.xml
    
    
